[FIX] Avoid syntax error on attribute_reference
seL4/camkes-tool pull request #90
Opened 2021-09-09 15:30 UTC by thowithc

The lexxer showed syntax errors when working with attribute references
using '<-'. The regular expression for angle_string is being checked by
the lexxer when encountering the '<' first.
So if the file to be parsed contains a '>' following the attribute
reference, the lexxer will tokenize everything from '<-' to this '>',
leading to a syntax error.
Examples for this behaviour would be an import statement with angled
brackes or an export statement containing '->'.
The proposed fix adds further characters to be excluded in the regular
expression, to avoid the angle_string rule to be active in such cases.

Signed-off-by: Thomas Wittal <thomas.wittal@hensoldt-cyber.de>

2021-09-09 17:52 UTC, axel-h approved these changes

2021-09-09 23:04 UTC, lsf37 requested changes
Thanks for that, the content looks good.

Just minor requests for adjusting the commit message:

We use the convention of a tag for which logic part of the repo the commit is for, unless it is something global (like a release commit or something like that). So the title could be for instance

```
parser: fix attribute_reference regex
```

In the body, it should be `lexer`, not `lexxer`.

2021-09-10 09:22 UTC, thowithc commented
Updated the commit message as proposed.

2021-09-11 01:07 UTC, lsf37 approved these changes
All good, thank you!

2021-09-11 01:35 UTC, merged